<?php

namespace TresorerieBundle\Repository;

/**
 * FactureAchatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FactureAchatRepository extends \Doctrine\ORM\EntityRepository
{




}
