<?php

namespace TresorerieBundle\Repository;

/**
 * FactureAchatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FactureAchatRepository extends \Doctrine\ORM\EntityRepository
{


    public  function calculerTotalAchat(){


        $qb=$this->getEntityManager()
            ->createQuery("SELECT sum (f.totalTTC) 
                            FROM TresorerieBundle:FactureAchat f 
                            ");

        return $qb->getSingleScalarResult();


    }
    public  function calculerTotalPaye(){


        $qb=$this->getEntityManager()
            ->createQuery("SELECT sum (f.totalPaye) 
                            FROM TresorerieBundle:FactureAchat f 
                            ");

        return $qb->getSingleScalarResult();


    }

    public  function calculerRestelPaye(){


        $qb=$this->getEntityManager()
            ->createQuery("SELECT sum (f.resteAPaye) 
                            FROM TresorerieBundle:FactureAchat f 
                            ");

        return $qb->getSingleScalarResult();


    }




}
