<?php

namespace TresorerieBundle\Repository;

/**
 * InventaireCaisseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InventaireCaisseRepository extends \Doctrine\ORM\EntityRepository
{
}
