<?php

namespace TresorerieBundle\Repository;

/**
 * LettreDeRelanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LettreDeRelanceRepository extends \Doctrine\ORM\EntityRepository
{
}
