<?php

namespace TresorerieBundle\Repository;

/**
 * RecouvrementClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecouvrementClientRepository extends \Doctrine\ORM\EntityRepository
{
}
