<?php

namespace TresorerieBundle\Repository;

/**
 * RecouvrementClientEspeceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecouvrementClientEspeceRepository extends \Doctrine\ORM\EntityRepository
{

    public  function calculerTotalRecouvrementEspece(){


        $qb=$this->getEntityManager()
            ->createQuery("SELECT sum (r.montant) 
                            FROM TresorerieBundle:RecouvrementClientEspece r where r.dateCreation = CURRENT_DATE()
                            ");

        return $qb->getSingleScalarResult();


    }


    public  function calculerTotal(){


        $qb=$this->getEntityManager()
            ->createQuery("SELECT sum (r.montant) 
                            FROM TresorerieBundle:RecouvrementClientEspece r
                            ");

        return $qb->getSingleScalarResult();


    }
}
