<?php

namespace TresorerieBundle\Repository;

/**
 * RecouvrementClientChequeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecouvrementClientChequeRepository extends \Doctrine\ORM\EntityRepository
{

    public  function calculerTotalRecouvrementCheque(){


        $qb=$this->getEntityManager()
            ->createQuery("SELECT sum (r.montant) 
                            FROM TresorerieBundle:RecouvrementClientCheque r where r.dateCreation = CURRENT_DATE()
                            ");

        return $qb->getSingleScalarResult();


    }
}
