<?php

namespace TresorerieBundle\Repository;

/**
 * ReglementFournisseurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReglementFournisseurRepository extends \Doctrine\ORM\EntityRepository
{
}
