<?php

namespace TresorerieBundle\Repository;

/**
 * ReglementFournisseurEspeceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReglementFournisseurEspeceRepository extends \Doctrine\ORM\EntityRepository
{
}
