<?php

namespace AchatBundle\Repository;

/**
 * BonEntreeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BonEntreeRepository extends \Doctrine\ORM\EntityRepository
{
}
