<?php

namespace AchatBundle\Repository;

/**
 * BonRetourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BonRetourRepository extends \Doctrine\ORM\EntityRepository
{
}
