<?php

namespace AchatBundle\Repository;

/**
 * CategorieAchatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieAchatRepository extends \Doctrine\ORM\EntityRepository
{
}
