<?php

namespace AchatBundle\Repository;

/**
 * ProduitAchatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitAchatRepository extends \Doctrine\ORM\EntityRepository
{
}
