<?php

namespace AchatBundle\Repository;

use AchatBundle\Entity\CategorieAchat;

/**
 * SousCategorieAchatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SousCategorieAchatRepository extends \Doctrine\ORM\EntityRepository
{
    public function findBys(CategorieAchat $cat){
        $qb = $this->createQueryBuilder('p')
            ->where('p.categorie = :c')
            ->setParameter('c',$cat);
        $query = $qb->getQuery();

        return $query->execute();
    }
}
