<?php

namespace AchatBundle\Repository;

/**
 * SousCategorieAchatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SousCategorieAchatRepository extends \Doctrine\ORM\EntityRepository
{
}
