<?php

namespace logistiqueBundle\Repository;

/**
 * aidechauffeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class aidechauffeurRepository extends \Doctrine\ORM\EntityRepository
{
}
