<?php

namespace logistiqueBundle\Repository;

/**
 * ordremissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ordremissionRepository extends \Doctrine\ORM\EntityRepository
{

    public function findByEtat(){
        $qb = $this->createQueryBuilder()
            ->select('', 'DESC');
        $query = $qb->getQuery();

        return $query->execute();
    }
}
