<?php

namespace StockageBundle\Repository;

/**
 * CommandeDAprovisionnementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeDAprovisionnementRepository extends \Doctrine\ORM\EntityRepository
{
}
