<?php

namespace StockageBundle\Repository;

/**
 * CommandeDAprovisionnementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeDAprovisionnementRepository extends \Doctrine\ORM\EntityRepository
{

    public  function updateE($id){


        $qb=$this->getEntityManager()
            ->createQuery("update set f.etat='facturer'
                             TresorerieBundle:FactureAchat f where f.id=?1
                            ")

            ->setParameter(1,$id);



    }


}
