<?php

namespace StockageBundle\Repository;

/**
 * InventaireStockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InventaireStockRepository extends \Doctrine\ORM\EntityRepository
{
}
