<?php

namespace StockageBundle\Repository;

/**
 * LigneCommandeDApprovisionnementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LigneCommandeDApprovisionnementRepository extends \Doctrine\ORM\EntityRepository
{
}
