<?php

namespace StockageBundle\Repository;

/**
 * LignePerteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LignePerteRepository extends \Doctrine\ORM\EntityRepository
{
}
