<?php

namespace StockageBundle\Repository;

/**
 * PerteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PerteRepository extends \Doctrine\ORM\EntityRepository
{
}
