<?php

namespace VenteBundle\Repository;

/**
 * CommandeVenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeVenteRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByTotal()
    {


        $qb=$this->getEntityManager()
            ->createQuery("SELECT sum (c.totalC)
                            FROM VenteBundle:CommandeVente c
                            ");

        return $qb->getSingleScalarResult();
    }

}
