<?php

namespace VenteBundle\Repository;

/**
 * FactureVenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FactureVenteRepository extends \Doctrine\ORM\EntityRepository
{

    public function findByNombre()
{
    $queryBuilder = $this->_em->createQueryBuilder()
        ->select('COUNT(e)')
        ->from('VenteBundle:FactureVente', 'e');

    return $queryBuilder->getQuery()->getSingleScalarResult();

}


}
