<?php

namespace VenteBundle\Repository;

/**
 * FactureVenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FactureVenteRepository extends \Doctrine\ORM\EntityRepository
{
}
