<?php

namespace VenteBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{

    public function findByName()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM VenteBundle:Produit '
            )
            ->getResult();
    }
}
