api_homepage:
    path:     /
    defaults: { _controller: ApiBundle:Default:index }
api_user_findAll:
    path:     /apiUser/findAll
    defaults: { _controller: ApiBundle:ApiUser:all }
api_user_add:
    path:     /apiUser/add
    defaults: { _controller: ApiBundle:ApiUser:new }
api_invrntaire_add:
    path:     /apiInventaire/add
    defaults: { _controller: ApiBundle:ApiInventaireCaisse:new }
api_inventaire_findAll:
    path:     /apiInventaire/findAll
    defaults: { _controller: ApiBundle:ApiInventaireCaisse:all }
api_inventaire_recupere:
    path:     /apiInventaire/recupere
    defaults: { _controller: ApiBundle:ApiInventaireCaisse:recuperer }
api_inventaire_delete:
    path:     /apiInventaire/delete
    defaults: { _controller: ApiBundle:ApiInventaireCaisse:delete }
api_lettre_add:
    path:     /apiLettre/new
    defaults: { _controller: ApiBundle:ApiLettreDeRelance:new }
api_lettre_allFacture:
    path:     /apiLettre/allF
    defaults: { _controller: ApiBundle:ApiLettreDeRelance:allFacture }
api_lettre_alle:
    path:     /apiLettre/all
    defaults: { _controller: ApiBundle:ApiLettreDeRelance:all }
api_lettre_delete:
    path:     /apiLettre/delete
    defaults: { _controller: ApiBundle:ApiLettreDeRelance:delete }

api_produit_affiche:
    path:     /apiProduit/affiche
    defaults: { _controller: ApiBundle:ApiProduit:affiche }



