api_homepage:
    path:     /
    defaults: { _controller: ApiBundle:Default:index }
api_user_findAll:
    path:     /apiUser/findAll
    defaults: { _controller: ApiBundle:ApiUser:all }
api_user_add:
    path:     /apiUser/add
    defaults: { _controller: ApiBundle:ApiUser:new }
api_user_modifier:
    path:     /apiUser/update
    defaults: { _controller: ApiBundle:ApiUser:modifier }
api_invrntaire_add:
    path:     /apiInventaire/add
    defaults: { _controller: ApiBundle:ApiInventaireCaisse:new }
api_inventaire_findAll:
    path:     /apiInventaire/findAll
    defaults: { _controller: ApiBundle:ApiInventaireCaisse:all }
api_inventaire_recupere:
    path:     /apiInventaire/recupere
    defaults: { _controller: ApiBundle:ApiInventaireCaisse:recuperer }
api_inventaire_delete:
    path:     /apiInventaire/delete
    defaults: { _controller: ApiBundle:ApiInventaireCaisse:delete }
api_inventaire_modifier:
    path:     /apiInventaire/modifier
    defaults: { _controller: ApiBundle:ApiInventaireCaisse:modifier }
api_enp_add:
    path:     /apiEntrepot/new
    defaults: { _controller: ApiBundle:ApiEntrepot:new }
api_enp_all:
    path:     /apiEntrepot/all
    defaults: { _controller: ApiBundle:ApiEntrepot:all }
api_comapp_add:
    path:     /apiCommandeDAp/new
    defaults: { _controller: ApiBundle:ApiCommandeDAprovisionnement:new }
api_comapp_all:
    path:     /apiCommandeDAp/all
    defaults: { _controller: ApiBundle:ApiCommandeDAprovisionnement:all }
api_comapp_delete:
    path:     /apiCommandeDAp/delete
    defaults: { _controller: ApiBundle:ApiCommandeDAprovisionnement:delete }
api_lignecomapp_add:
    path:     /apiLigneCommandeDAp/new
    defaults: { _controller: ApiBundle:ApiLigneCommandeDApprovisionnement:new }
api_lignecomapp_all:
    path:     /apiLigneCommandeDAp/all
    defaults: { _controller: ApiBundle:ApiLigneCommandeDApprovisionnement:all }
api_lignecomapp_delete:
    path:     /apiLigneCommandeDAp/delete
    defaults: { _controller: ApiBundle:ApiLigneCommandeDApprovisionnement:delete }
api_perte_add:
    path:     /apiPerte/new
    defaults: { _controller: ApiBundle:ApiPerte:new }
api_perte_all:
    path:     /apiPerte/all
    defaults: { _controller: ApiBundle:ApiPerte:all }
api_perte_delete:
    path:     /apiPerte/delete
    defaults: { _controller: ApiBundle:ApiPerte:delete }
api_inv_add:
    path:     /apiInvent/new
    defaults: { _controller: ApiBundle:ApiInventaire:new }
api_inv_all:
    path:     /apiInvent/all
    defaults: { _controller: ApiBundle:ApiInventaire:all }
api_inv_delete:
    path:     /apiInvent/delete
    defaults: { _controller: ApiBundle:ApiInventaire:delete }
api_ligneperte_add:
    path:     /apiLignePerte/new
    defaults: { _controller: ApiBundle:ApiLignePerte:new }
api_ligneperte_all:
    path:     /apiLignePerte/all
    defaults: { _controller: ApiBundle:ApiLignePerte:all }
api_ligneperte_delete:
    path:     /apiLignePerte/delete
    defaults: { _controller: ApiBundle:ApiLignePerte:delete }
api_empl_add:
    path:     /apiEmp/new
    defaults: { _controller: ApiBundle:ApiEmplacement:new }
api_empl_all:
    path:     /apiEmp/all
    defaults: { _controller: ApiBundle:ApiEmplacement:all }
api_empl_delete:
    path:     /apiEmp/delete
    defaults: { _controller: ApiBundle:ApiEmplacement:delete }
api_lettre_add:
    path:     /apiLettre/new
    defaults: { _controller: ApiBundle:ApiLettreDeRelance:new }
api_lettre_allFacture:
    path:     /apiLettre/allF
    defaults: { _controller: ApiBundle:ApiLettreDeRelance:allFacture }
api_lettre_alle:
    path:     /apiLettre/all
    defaults: { _controller: ApiBundle:ApiLettreDeRelance:all }
api_lettre_delete:
    path:     /apiLettre/delete
    defaults: { _controller: ApiBundle:ApiLettreDeRelance:delete }

api_produit_affiche:
    path:     /apiProduit/affiche
    defaults: { _controller: ApiBundle:ApiProduit:affiche }

api_aideCh_affiche:
    path:     /apiaide/affiche
    defaults: { _controller: ApiBundle:ApiAidechauffeur:affaide }

api_ordreM_affiche:
    path:     /apiordre/affiche
    defaults: { _controller: ApiBundle:ApiOrdreDeMission:afficheordre }
api_ordreM_ajout:
    path:     /apiordre/ajout
    defaults: { _controller: ApiBundle:ApiOrdreDeMission:ajoutordreM }

api_ordreM_rec:
    path:     /apiordre/rec
    defaults: { _controller: ApiBundle:ApiOrdreDeMission:recM }

api_aideCh_Ajout:
    path:     /apiAchauf/ajout
    defaults: { _controller: ApiBundle:ApiAidechauffeur:ajoutAchauf }


api_ajout_commandeV:
    path:     /apiCommandeVente/ajout
    defaults: { _controller: ApiBundle:ApiCommande:ajoutercom }



api_ajout_ligne:
    path:     /apiLigneCommande/ajout
    defaults: { _controller: ApiBundle:ApiCommande:ajouterLigne }

api_affiche_commande:
    path:     /apiCommandeVente/affiche
    defaults: { _controller: ApiBundle:ApiCommande:show }


api_affiche_commandeMax:
    path:     /apiCommandeVente/max
    defaults: { _controller: ApiBundle:ApiCommande:maxCommande }

api_ajout_bon:
    path:     /apiBon/ajout/{id}
    defaults: { _controller: ApiBundle:ApiCommande:ajouterBonLivraison }
api_Ch_Ajout:
    path:     /apichauf/ajout
    defaults: { _controller: ApiBundle:ApiChauffeur:ajoutchauf }

api_Ch_Affiche:
    path:     /apichauf/affiche
    defaults: { _controller: ApiBundle:ApiChauffeur:chauffeuraff}

api_v_Affiche:
    path:     /apiv/affiche
    defaults: { _controller: ApiBundle:ApiVehicule:affichevehicule}

api_v_Ajout:
    path:     /apiv/ajout
    defaults: { _controller: ApiBundle:ApiVehicule:ajoutvehicule}

api_F_Ajout:
    path:     /apiF/ajout
    defaults: { _controller: ApiBundle:Fournisseur:index}

api_F_Affiche:
    path:     /apiF/affiche
    defaults: { _controller: ApiBundle:Fournisseur:new}

api_B_Affiche:
    path:     /apiB/affiche
    defaults: { _controller: ApiBundle:ApiBonEntree:index}

list_prod:
    path:     /apiP/listP
    defaults: { _controller: "ApiBundle:ApiProduit:ListProduct" }
add_prod:
    path:     /apiP/addP
    defaults: { _controller: "ApiBundle:ApiProduit:AddProduct" }
Listfournisseur:
    path:     /apiF/listF
    defaults: { _controller: "ApiBundle:ApiFournisseur:listFounisseur" }
add_fourn:
    path:     /apiF/addF
    defaults: { _controller: "ApiBundle:ApiFournisseur:AddFournisseur" }
liste_Sous_Cat:
    path:     /listSousCat
    defaults: { _controller: "AchatBundle:ProduitAchat:ListeSouCategorie" }
liste_comm:
    path:     /listComm
    defaults: { _controller: "AchatBundle:ProduitAchat:ListeCommandeApprovisionnement" }
liste_bon_entree:
    path:     /apiBE/listBonEntree
    defaults: { _controller: "ApiBundle:ApiBonEntree:ListeBonEntree" }
liste_bon_retour:
    path:     /apiBR/listBonretour
    defaults: { _controller: "ApiBundle:ApiBonRetour:ListeBonRetour" }
add_bon_entree:
    path:     /apiBE/addBonEntree
    defaults: { _controller: "ApiBundle:ApiBonEntree:AddBonentree" }
add_bon_retour:
    path:     /apiBR/addBonRetour
    defaults: { _controller: "ApiBundle:ApiBonRetour:AddBonRetour" }
edit_prod:
    path:     /apiP/editP
    defaults: { _controller: "ApiBundle:ApiProduit:editProduct" }
edit_fourn:
    path:     /apiF/editF
    defaults: { _controller: "ApiBundle:ApiFournisseur:editFournisseur" }
delete_prod:
    path:     /apiP/deleteP/{id}
    defaults: { _controller: "ApiBundle:ApiProduit:deleteProduct" }
delete_fourn:
    path:     /apiF/deleteF/{id}
    defaults: { _controller: "ApiBundle:ApiFournisseur:deletefournisseur" }
delete_bon_entree:
    path:     /apiBE/deletebonentree/{id}
    defaults: { _controller: "ApiBundle:ApiBonEntree:deletebonentree" }
delete_bon_retour:
    path:     /apiBR/deletebonretour/{id}
    defaults: { _controller: "ApiBundle:ApiBonRetour:deletebonRetour" }

affi_bon:
    path:     /apio/affiche
    defaults: { _controller: "ApiBundle:ApiOrdreDeMission:affiche" }

aupdate_bon:
    path:     /apibonn/update
    defaults: { _controller: "ApiBundle:ApiOrdreDeMission:update" }

delete_Ordre:
    path:     /apiOrdreD/delete/{id}
    defaults: { _controller: "ApiBundle:ApiOrdreDeMission:deleteM" }