categorie_index:
    path:     /
    defaults: { _controller: "AchatBundle:CategorieAchat:index" }
    methods:  GET

categorie_show:
    path:     /{id}/show
    defaults: { _controller: "AchatBundle:CategorieAchat:show" }
    methods:  GET

categorie_cat:
    path:     /{id}/prods
    defaults: { _controller: "AchatBundle:SousCategorieAchat:prods" }
    methods:  GET

categorie_new:
    path:     /new
    defaults: { _controller: "AchatBundle:CategorieAchat:new" }
    methods:  [GET, POST]

categorie_edit:
    path:     /{id}/edit
    defaults: { _controller: "AchatBundle:CategorieAchat:edit" }
    methods:  [GET, POST]

categorie_delete:
    path:     /{id}/delete
    defaults: { _controller: "AchatBundle:CategorieAchat:delete" }
    methods:  DELETE
